# Generated by Django 5.2.1 on 2025-06-16 22:21

import django.core.validators
import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_alter_categorias_options_remove_categorias_codigo'),
        ('empleados', '0006_empleados_codigo_empleado_empleados_correo_inst'),
        ('estados', '0001_initial'),
        ('proveedores', '0002_alter_proveedores_descripcion_and_more'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BienNacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=inventario.models.bien_image_upload_path, verbose_name='Imagen del Bien')),
                ('nombre_bien', models.CharField(max_length=100, verbose_name='Nombre del Bien')),
                ('numero_modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número del Modelo')),
                ('serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial')),
                ('numero_inventario', models.CharField(max_length=20, unique=True, verbose_name='Número de Inventario')),
                ('unidad_medida', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad de Medida')),
                ('cantidad_minima', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima')),
                ('total', models.PositiveIntegerField(default=1, verbose_name='Total')),
                ('disponibles', models.PositiveIntegerField(default=1, verbose_name='Disponibles')),
                ('cantidad_restante', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Bien Restante')),
                ('total_asignado', models.PositiveIntegerField(default=0, verbose_name='Total Asignado')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Costo de Compra')),
                ('numero_orden', models.CharField(blank=True, max_length=60, null=True, verbose_name='Número de Orden')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categorias', verbose_name='Categoría')),
                ('estado_fisico', models.ManyToManyField(blank=True, to='estados.estados', verbose_name='Etiquetas de Estado')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedores', verbose_name='Proveedor')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleados', verbose_name='Responsable Actual')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.ubicaciones', verbose_name='Ubicación Física')),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.compania', verbose_name='Compañía')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.fabricante', verbose_name='Fabricante')),
                ('manufacturera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.manufacturera', verbose_name='Manufacturera')),
            ],
            options={
                'verbose_name_plural': 'Bienes Nacionales',
                'ordering': ['nombre_bien', 'numero_inventario'],
            },
        ),
    ]
