# Generated by Django 5.2.1 on 2025-06-17 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('subcategorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biennacional',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subcategorias.subcategorias', verbose_name='Subcategoría'),
        ),
    ]
