# Generated by Django 5.2.1 on 2025-06-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categorias_options_remove_categorias_codigo'),
        ('inventario', '0002_biennacional_subcategoria'),
        ('subcategorias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biennacional',
            name='cantidad_minima',
        ),
        migrations.RemoveField(
            model_name='biennacional',
            name='cantidad_restante',
        ),
        migrations.RemoveField(
            model_name='biennacional',
            name='disponibles',
        ),
        migrations.RemoveField(
            model_name='biennacional',
            name='total',
        ),
        migrations.RemoveField(
            model_name='biennacional',
            name='total_asignado',
        ),
        migrations.CreateModel(
            name='StockBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bien', models.CharField(max_length=100)),
                ('numero_modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_minima', models.PositiveIntegerField(default=0, verbose_name='Cantidad Mínima')),
                ('cantidad_restante', models.PositiveIntegerField(default=0, verbose_name='Cantidad Restante')),
                ('total_asignado', models.PositiveIntegerField(default=0, verbose_name='Total Asignado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categorias')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subcategorias.subcategorias')),
            ],
            options={
                'verbose_name_plural': 'Stock de Bienes',
                'ordering': ['nombre_bien', 'categoria', 'subcategoria', 'numero_modelo'],
                'unique_together': {('nombre_bien', 'categoria', 'subcategoria', 'numero_modelo')},
            },
        ),
    ]
