# Generated by Django 5.2.1 on 2025-06-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categorias_options_remove_categorias_codigo'),
        ('inventario', '0003_remove_biennacional_cantidad_minima_and_more'),
        ('subcategorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockbien',
            options={'ordering': ['nombre_bien', 'categoria', 'subcategoria'], 'verbose_name_plural': 'Stock de Bienes'},
        ),
        migrations.AlterUniqueTogether(
            name='stockbien',
            unique_together={('nombre_bien', 'categoria', 'subcategoria')},
        ),
        migrations.RemoveField(
            model_name='stockbien',
            name='numero_modelo',
        ),
    ]
