# Generated by Django 5.2.1 on 2025-07-03 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_stockbien_options_and_more'),
        ('objeto_gasto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biennacional',
            name='objeto_gasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objeto_gasto.objetogasto', verbose_name='Objeto de Gasto'),
        ),
    ]
