# Generated by Django 5.2.1 on 2025-06-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0002_alter_proveedores_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre_cambio', models.CharField(max_length=60, verbose_name='Nombre')),
                ('descripcion_cambio', models.CharField(max_length=120)),
                ('telefono_cambio', models.CharField(max_length=120)),
                ('correo_cambio', models.CharField(max_length=100)),
                ('direccion_cambio', models.CharField(max_length=150)),
                ('activo', models.BooleanField()),
                ('creado_fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_modificacion_cambio', models.DateTimeField(auto_now=True)),
                ('eliminado_cambio', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='proveedores.proveedores')),
            ],
            options={
                'db_table': 'proveedores_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
