# Generated by Django 5.2.1 on 2025-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores_history',
            old_name='activo',
            new_name='activo_cambio',
        ),
        migrations.AlterField(
            model_name='proveedores_history',
            name='eliminado_cambio',
            field=models.BooleanField(),
        ),
    ]
