# Generated by Django 5.2.1 on 2025-05-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0005_alter_pantalla_identificador_alter_pantalla_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre_cambio', models.CharField(max_length=50)),
                ('descripcion_cambio', models.CharField(max_length=160)),
                ('eliminado_cambio', models.BooleanField()),
                ('usuarios_cambio', models.TextField(help_text='Lista de usernames, separados por coma')),
                ('pantallas_cambio', models.TextField(help_text='Lista de identificadores, separados por coma')),
                ('fecha_de_creacion_cambio', models.DateTimeField()),
                ('fecha_de_modificacion_cambio', models.DateTimeField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='roles.roles')),
            ],
        ),
    ]
