# Generated by Django 5.2.1 on 2025-06-02 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('color_hex', models.CharField(blank=True, help_text='Opcional. Si se omite, se mostrará un gris neutro.', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Color HEX inválido, ej. #34A853', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Color (HEX)')),
                ('descripcion', models.CharField(max_length=120)),
                ('eliminado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estados',
                'ordering': ['nombre'],
            },
        ),
    ]
