# Generated by Django 5.2.1 on 2025-07-03 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('descripcion', models.CharField(blank=True, max_length=120)),
                ('creado_fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'objetos de gasto',
                'ordering': ['nombre'],
            },
        ),
    ]
