# Generated by Django 5.2.1 on 2025-06-26 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_alter_stockbien_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BienNacionalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre_bien', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=80)),
                ('subcategoria', models.CharField(blank=True, max_length=80, null=True)),
                ('numero_modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=80, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=120, null=True)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_inventario', models.CharField(max_length=20)),
                ('unidad_medida', models.CharField(blank=True, max_length=30, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('numero_orden', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.biennacional')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Historial de Bien Nacional',
                'verbose_name_plural': 'Historial de Bienes Nacionales',
                'ordering': ['-timestamp'],
            },
        ),
    ]
