# Generated by Django 5.2.1 on 2025-06-26 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biennacionalhistory',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biennacionalhistory',
            name='estado_fisico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biennacionalhistory',
            name='manufacturera',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='biennacionalhistory',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biennacionalhistory',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
