# Generated by Django 5.2.1 on 2025-07-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_history', '0002_biennacionalhistory_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biennacionalhistory',
            name='objeto_gasto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='biennacionalhistory',
            name='categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
