# Generated by Django 5.2.1 on 2025-07-03 19:22

import solicitud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbien',
            name='memo',
            field=models.FileField(blank=True, null=True, upload_to=solicitud.models.bien_memo_upload_path, verbose_name='Memo de Solicitud'),
        ),
    ]
