# Generated by Django 5.2.1 on 2025-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones_history',
            name='fecha_aceptado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
