# Generated by Django 5.2.1 on 2025-07-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones_history', '0002_asignaciones_history_fecha_aceptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones_history',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, upload_to='assets/asignaciones/firmados/', verbose_name='PDF Firmado'),
        ),
    ]
