# Generated by Django 5.2.1 on 2025-07-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones_history', '0003_asignaciones_history_pdf_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones_history',
            name='fecha_descargo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
