# Generated by Django 5.2.1 on 2025-05-24 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales ni numeros, solo letras', regex='^[a-zA-Z]+$'), django.core.validators.RegexValidator(message='La primera letra debe ser mayuscula, el campo no permite letras mayusculas luego de la primera letra', regex='^[A-Z][a-z]*$'), django.core.validators.RegexValidator(message='No se permite mas de una palabra en el campo.', regex='^[^\\s]+$'), django.core.validators.RegexValidator(message='El campo no permite tres mismas letras seguidas o mas.', regex='^(?:(?!(\\w)\\1\\1).)+$')])),
                ('cargo', models.CharField(max_length=80)),
                ('dependencia', models.CharField(max_length=80)),
                ('contacto', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=False)),
                ('creado_fecha', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
