# Generated by Django 5.2.1 on 2025-05-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='fecha_de_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
