# Generated by Django 5.2.1 on 2025-05-28 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleados_fecha_de_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Sólo letras y espacios. Después se convertirá todo a mayúsculas.', regex='^[A-Za-z\\s]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='contacto',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Contacto sólo puede tener dígitos, espacios, + y -.', regex='^[0-9+\\-\\s]+$'), django.core.validators.MaxLengthValidator(120, 'Máximo 120 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='dependencia',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Sólo letras y espacios. Después se convertirá todo a mayúsculas.', regex='^[A-Za-z\\s]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Sólo letras y espacios. Después se convertirá todo a mayúsculas.', regex='^[A-Za-z\\s]+$'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(120)]),
        ),
    ]
