# Generated by Django 5.2.1 on 2025-05-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0001_initial'),
        ('empleados', '0004_alter_empleados_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dependencias.dependencias'),
        ),
    ]
