# Generated by Django 5.2.1 on 2025-06-02 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleados_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='codigo_empleado',
            field=models.CharField(default=0, help_text='Exactamente 4 dígitos, p.ej. 7016', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='El código de empleado debe tener exactamente 4 dígitos, p.ej. "7016".', regex='^\\d{4}$')], verbose_name='Código de empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='correo_inst',
            field=models.CharField(default=2, help_text='Debe terminar en @utpoliticalimpia.hn', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Debes usar tu correo institucional terminando en @utpoliticalimpia.hn', regex='^[\\w\\.\\-]+@utpoliticalimpia\\.hn$'), django.core.validators.EmailValidator(message='Formato de correo inválido.')], verbose_name='Correo institucional'),
            preserve_default=False,
        ),
    ]
