# Generated by Django 5.2.1 on 2025-06-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_empleados_codigo_empleado_empleados_correo_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='num_identidad',
            field=models.CharField( help_text='Debe contener 13 digitos en total, separados por guiones p.ej. 0801-2000-00000', max_length=15, unique=True, verbose_name='Numero de Identidad'),
            preserve_default=False,
        ),
    ]
