# Generated by Django 5.2.1 on 2025-06-17 22:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_alter_categorias_options_remove_categorias_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('descripcion', models.CharField(blank=True, max_length=120)),
                ('creado_fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='categorias.categorias')),
            ],
            options={
                'verbose_name_plural': 'subcategorías',
                'ordering': ['nombre'],
            },
        ),
    ]
