# Generated by Django 5.2.1 on 2025-06-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'categorías'},
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='codigo',
        ),
    ]
