# Generated by Django 5.2.1 on 2025-07-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categorias_options_remove_categorias_codigo'),
        ('objeto_gasto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='objeto_gasto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='objeto_gasto.objetogasto'),
            preserve_default=False,
        ),
    ]
