# Generated by Django 5.2.1 on 2025-07-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias_history',
            name='objeto_gasto_cambio',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
