# Generated by Django 5.2.1 on 2025-05-25 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_roles_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='fecha_de_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
