# Generated by Django 5.2.1 on 2025-05-28 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_roles_fecha_de_creacion_roles_fecha_de_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantalla',
            name='identificador',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El identificador solo permite minúsculas, números, guiones bajos, "/" o ":"', regex='^[a-z0-9_/:-]+$')], verbose_name='Ruta/ID'),
        ),
        migrations.AlterField(
            model_name='pantalla',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre solo permite letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$'), django.core.validators.MinLengthValidator(3)], verbose_name='Nombre de la pantalla'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='descripcion',
            field=models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='La descripción no permite caracteres extraños.', regex='^[\\wÁÉÍÓÚáéíóúÑñ\\s\\.,;:¡!¿?\\"\\\'\\-\\(\\)]+$'), django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(160)]),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El nombre solo permite letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
