# Generated by Django 5.2.1 on 2025-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionbien',
            name='fecha_aceptado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionbien',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de firma'), ('proceso', 'En Proceso'), ('firmado', 'Firmado/Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
