# Generated by Django 5.2.1 on 2025-07-04 20:11

import asignaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_asignacionbien_fecha_aceptado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionbien',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, upload_to=asignaciones.models.firma_documento_upload_path, verbose_name='PDF Firmado'),
        ),
    ]
