# Generated by Django 5.2.1 on 2025-07-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_asignacionbien_pdf_firmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionbien',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'Proceso'), ('firmado', 'Firmado'), ('cancelado', 'Cancelado'), ('penddesc', 'PendDesc'), ('descargado', 'Descargado')], default='pendiente', max_length=20),
        ),
    ]
