# Generated by Django 5.2.1 on 2025-07-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_alter_asignacionbien_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionbien',
            name='fecha_descargo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
