# Generated by Django 5.2.1 on 2025-05-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_alter_empleados_cargo_alter_empleados_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre_cambio', models.CharField(max_length=50)),
                ('cargo_cambio', models.CharField(max_length=90)),
                ('dependencia_cambio', models.CharField(max_length=80)),
                ('contacto_cambio', models.CharField(max_length=120)),
                ('activo_cambio', models.BooleanField()),
                ('creado_fecha_cambio', models.DateTimeField()),
                ('fecha_de_modificacion_cambio', models.DateTimeField()),
                ('eliminado_cambio', models.BooleanField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='empleados.empleados')),
            ],
        ),
    ]
