# Generated by Django 5.2.1 on 2025-06-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_history', '0002_empleados_history_changed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados_history',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='empleados_history',
            name='codigo_empleado_cambio',
            field=models.CharField(default=2, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados_history',
            name='correo_inst_cambio',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='empleados_history',
            table='empleados_history',
        ),
    ]
