# Generated by Django 5.2.1 on 2025-06-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_history', '0003_alter_empleados_history_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados_history',
            name='numero_identidad_cambio',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
