# Generated by Django 5.2.1 on 2025-06-03 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Sólo letras y espacios. Después se convertirá todo a mayúsculas.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')], verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Sólo letras y espacios. Después se convertirá todo a mayúsculas.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')], verbose_name='Descripción')),
                ('telefono', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Contacto sólo puede tener dígitos, espacios, + y -.', regex='^[0-9+\\-\\s]+$'), django.core.validators.MaxLengthValidator(120, 'Máximo 120 caracteres.')])),
                ('correo', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Ingresa un correo electrónico válido (p.ej. usuario@dominio.com).', regex='^[\\w\\.\\+\\-]+@[\\w\\-]+\\.[A-Za-z]{2,}$'), django.core.validators.EmailValidator(message='Formato de correo inválido.')], verbose_name='Correo')),
                ('direccion', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='La dirección sólo puede contener letras, números, espacios y comas.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\\s,]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')], verbose_name='Dirección')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('creado_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-creado_fecha'],
            },
        ),
    ]
