# Generated by Django 5.2.1 on 2025-06-03 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='descripcion',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='El nombre sólo puede contener letras, números, espacios y comas.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\\s,.]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='El nombre sólo puede contener letras, números, espacios y comas.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\\s,.]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')], verbose_name='Nombre'),
        ),
    ]
