# Generated by Django 5.2.1 on 2025-06-17 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategorias_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre_cambio', models.CharField(max_length=80)),
                ('descripcion_cambio', models.CharField(blank=True, max_length=120)),
                ('categoria_cambio', models.CharField(max_length=80)),
                ('creado_fecha_cambio', models.DateTimeField()),
                ('fecha_de_modificacion_cambio', models.DateTimeField()),
                ('eliminado_cambio', models.BooleanField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='subcategorias.subcategorias')),
            ],
            options={
                'verbose_name_plural': 'Historial de subcategorías',
                'ordering': ['-timestamp'],
            },
        ),
    ]
