# Generated by Django 5.2.1 on 2025-06-01 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Sólo letras y espacios. Después se convertirá todo a mayúsculas.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')], verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Sólo letras y espacios. Después se convertirá todo a mayúsculas.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$'), django.core.validators.MinLengthValidator(2, 'Mínimo 2 caracteres.'), django.core.validators.MaxLengthValidator(80, 'Máximo 80 caracteres.')], verbose_name='Descripción')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('creado_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fecha_de_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['-creado_fecha'],
            },
        ),
    ]
