# Generated by Django 5.2.1 on 2025-06-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre_cambio', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('color_hex_cambio', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color (HEX)')),
                ('descripcion_cambio', models.CharField(max_length=120)),
                ('eliminado_cambio', models.BooleanField(default=False)),
                ('creado_en_cambio', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en_cambio', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='estados.estados')),
            ],
            options={
                'db_table': 'estados_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
