# Generated by Django 5.2.1 on 2025-06-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estados_history',
            old_name='empleado',
            new_name='estado',
        ),
    ]
