# Generated by Django 5.2.1 on 2025-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados_history', '0002_rename_empleado_estados_history_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_history',
            name='nombre_cambio',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
